# Generated by Django 3.1.5 on 2021-03-22 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20210321_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method', to='cart.paymentmethod')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pays', to='cart.order')),
            ],
        ),
    ]
