# Generated by Django 3.0.3 on 2021-04-23 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20210323_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(choices=[('R', 'ROUND'), ('O', 'OVAL'), ('P', 'PRINCESS')], max_length=1)),
                ('quality', models.CharField(choices=[(1, 'GH/VS'), (2, 'F.Y/VSI')], max_length=1)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('weight', models.IntegerField(default=0)),
                ('gold_caliber', models.PositiveIntegerField(default=1)),
                ('gold_weight', models.IntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stones', to='cart.Product')),
            ],
        ),
    ]
