# Generated by Django 3.0.3 on 2021-04-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_stone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stone',
            name='quality',
            field=models.CharField(choices=[('1', 'GH/VS'), ('2', 'F.Y/VSI')], max_length=1),
        ),
    ]
