# Generated by Django 3.0.3 on 2021-04-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_tax'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SizeVariation',
        ),
        migrations.AlterField(
            model_name='diamond',
            name='quality',
            field=models.CharField(choices=[('GH/VS', 'GH/VS'), ('F.Y/VSI', 'F.Y/VSI')], max_length=20),
        ),
        migrations.AlterField(
            model_name='diamond',
            name='shape',
            field=models.CharField(choices=[('ROUND', 'ROUND'), ('OVAL', 'OVAL'), ('PRINCESS', 'PRINCESS')], max_length=20),
        ),
    ]
